feat(test): test

diff --git a/.github/workflows/ci_s3_deploy_multi_environment.yml b/.github/workflows/ci_s3_deploy_multi_environment.yml
--- a/.github/workflows/ci_s3_deploy_multi_environment.yml
+++ b/.github/workflows/ci_s3_deploy_multi_environment.yml
@@ -266,36 +266,52 @@ jobs:
                 else
                   .
                 end
+              )
+            ')
+          fi
 
+          # Salva configuração atualizada
+          echo "$UPDATED_CONFIG" > dist-updated.json
 
-            - name: Verify if has some invalidation with "/*" path
-              id: check_full_invalidation
-              run: |
-                DIST_ID="${CLOUDFRONT_DISTRIBUTION_ID}"
-                
-                echo "🔍 Searching invalidations"
-                IDS=$(aws cloudfront list-invalidations \
-                  --distribution-id "$DIST_ID" \
-                  --query "InvalidationList.Items[].Id" \
-                  --output text)
+          # Atualiza distribuição com o --if-match correto
+          aws cloudfront update-distribution \
+            --id "$DIST_ID" \
+            --distribution-config file://dist-updated.json \
+            --if-match "$ETAG"
+        env:
+          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          AWS_REGION: ${{ secrets.AWS_REGION }}
+          CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
 
-                FOUND="no"
+      - name: Verify if has some invalidation with "/*" path
+        id: check_full_invalidation
+        run: |
+          DIST_ID="${CLOUDFRONT_DISTRIBUTION_ID}"
+          
+          echo "🔍 Searching invalidations"
+          IDS=$(aws cloudfront list-invalidations \
+            --distribution-id "$DIST_ID" \
+            --query "InvalidationList.Items[].Id" \
+            --output text)
 
-                for ID in $IDS; do
-                  MATCH=$(aws cloudfront get-invalidation \
-                    --distribution-id "$DIST_ID" \
-                    --id "$ID" \
-                    --query "Invalidation.InvalidationBatch.Paths.Items" \
-                    --output text | grep -Fx "/*" || true)
+          FOUND="no"
 
-                  if [[ "$MATCH" == "/*" ]]; then
-                    FOUND="yes"
-                    break
-                  fi
-                done
+          for ID in $IDS; do
+            MATCH=$(aws cloudfront get-invalidation \
+              --distribution-id "$DIST_ID" \
+              --id "$ID" \
+              --query "Invalidation.InvalidationBatch.Paths.Items" \
+              --output text | grep -Fx "/*" || true)
 
-                echo "✅ Invalidation founded? $FOUND"
-                echo "has_full_invalidation=$FOUND" >> "$GITHUB_OUTPUT"
+            if [[ "$MATCH" == "/*" ]]; then
+              FOUND="yes"
+              break
+            fi
+          done
+
+          echo "✅ Invalidation founded? $FOUND"
+          echo "has_full_invalidation=$FOUND" >> "$GITHUB_OUTPUT"
         env:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
