feat(preview): adds preview url

diff --git a/.github/workflows/ci_s3_deploy_multi_environment.yml b/.github/workflows/ci_s3_deploy_multi_environment.yml
--- a/.github/workflows/ci_s3_deploy_multi_environment.yml
+++ b/.github/workflows/ci_s3_deploy_multi_environment.yml
@@ -159,30 +159,100 @@ jobs:
       name: ${{ inputs.environment_type }}
 
     steps:
-      - name: Get S3 website endpoint
-        if: github.event_name == 'pull_request'
-        id: get_s3_website_endpoint
+      - name: Verify if has some invalidation with "/*" path
+        id: check_full_invalidation
         run: |
-          BUCKET_NAME="${{ secrets.S3_BUCKET_NAME }}"
-          AWS_REGION="${{ secrets.AWS_REGION }}"
+          DIST_ID="${CLOUDFRONT_DISTRIBUTION_ID}"
+          
+          echo "🔍 Searching invalidations"
+          IDS=$(aws cloudfront list-invalidations \
+            --distribution-id "$DIST_ID" \
+            --query "InvalidationList.Items[].Id" \
+            --output text)
+
+          FOUND="no"
+
+          for ID in $IDS; do
+            MATCH=$(aws cloudfront get-invalidation \
+              --distribution-id "$DIST_ID" \
+              --id "$ID" \
+              --query "Invalidation.InvalidationBatch.Paths.Items" \
+              --output text | grep -Fx "/*" || true)
+
+            if [[ "$MATCH" == "/*" ]]; then
+              FOUND="yes"
+              break
+            fi
+          done
+
+          echo "✅ Invalidation founded? $FOUND"
+          echo "has_full_invalidation=$FOUND" >> "$GITHUB_OUTPUT"
+        env:
+          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          AWS_REGION: ${{ secrets.AWS_REGION }}
+          CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
+  
+      - name: Invalidate CloudFront cache (index.html ONLY)
+        if: ${{ steps.check_full_invalidation.outputs.has_full_invalidation == 'yes' }}
+        run: |
+          aws cloudfront create-invalidation \
+            --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/index.html"
+        env:
+          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          AWS_REGION: ${{ secrets.AWS_REGION }}
+          CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}  
+          
+      - name: Invalidate CloudFront cache (ALL)
+        if: ${{ steps.check_full_invalidation.outputs.has_full_invalidation == 'no' }}
+        run: |
+          aws cloudfront create-invalidation \
+            --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
+        env:
+          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          AWS_REGION: ${{ secrets.AWS_REGION }}
+          CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
+        
+      - name: Get CloudFront Domain Name and Alternate Name
+        id: get_cf_domain
+        run: |
+          DOMAIN_NAME=$(aws cloudfront get-distribution --id $CLOUDFRONT_DISTRIBUTION_ID \
+            --query 'Distribution.DomainName' --output text)
       
-          WEBSITE_ENDPOINT="http://${BUCKET_NAME}.s3-website-${AWS_REGION}.amazonaws.com"
-          echo "website_endpoint=$WEBSITE_ENDPOINT" >> "$GITHUB_OUTPUT"
+          ALTERNATE_NAME=$(aws cloudfront get-distribution --id $CLOUDFRONT_DISTRIBUTION_ID \
+            --query 'Distribution.DistributionConfig.Aliases.Items[0]' --output text)
+      
+          echo "Domain name is: $DOMAIN_NAME"
+          echo "Alternate domain (CNAME) is: $ALTERNATE_NAME"
+      
+          echo "domain_name=$DOMAIN_NAME" >> "$GITHUB_OUTPUT"
+          echo "alternate_name=$ALTERNATE_NAME" >> "$GITHUB_OUTPUT"
+        env:
+          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          AWS_REGION: ${{ secrets.AWS_REGION }}
+          CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
         
       - name: Output preview URL
         uses: actions/github-script@v6
         if: github.event_name == 'pull_request'
         env:
-          S3_ENDPOINT: ${{ steps.get_s3_website_endpoint.outputs.website_endpoint }}
           APP_PREFIX: ${{ env.APP_PREFIX }}
+          DOMAIN_NAME: ${{ steps.get_cf_domain.outputs.domain_name }}
+          ALTERNATE_DOMAIN: ${{ steps.get_cf_domain.outputs.alternate_name }}
         with:
           github-token: ${{ secrets.WF_GITHUB_TOKEN }}
           script: |
             const prNumber = context.payload.pull_request.number;
-            const s3Endpoint = process.env.S3_ENDPOINT;
             const previewPrefix = process.env.APP_PREFIX;
+            const domainName = process.env.DOMAIN_NAME;
+            const alternateDomain = process.env.ALTERNATE_DOMAIN;
+
+            const selectedDomain = alternateDomain !== "None" && domainName !== "None" ? `https://${alternateDomain}` : `https://${domainName}`;
       
-            const previewUrl = `${s3Endpoint}/${previewPrefix}`;
+            const previewUrl = `${selectedDomain}/${previewPrefix}`;
       
             await github.rest.issues.createComment({
               issue_number: prNumber,
